# coding: utf-8

"""
    Gencove Back API

    API for Gencove REST service. Visit <a href='https://gencove.com/'>gencove.com</a> and <a href='https://docs.gencove.com/'>docs.gencove.com</a> for more information. <br><hr><p>To work with Insomnia, you can generate a Gencove API key by <a target='_blank' href='https://web.gencove.com/account?filter=api-keys'>clicking here</a>. Once you have the API key and have imported the project in Insomnia as a <i>Request Collection</i>, enter the key in Insomnia under <i>Manage Environment</i>.</p><a href='https://insomnia.rest/run/?label=back_api2&uri=https%3A%2F%2Fv2-api-files-prod.s3.amazonaws.com%2Fpublic%2Finsomnia%2Finsomnia_gencove_prod.json' target='_blank'>Run in Insomnia</a><hr>

    The version of the OpenAPI document: v2
    Contact: info@gencove.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gencove_client.api.sample_api import SampleApi


class TestSampleApi(unittest.TestCase):
    """SampleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SampleApi()

    def tearDown(self) -> None:
        pass

    def test_sample_ancestry_read(self) -> None:
        """Test case for sample_ancestry_read"""
        pass

    def test_sample_manifests_csv_template_list(self) -> None:
        """Test case for sample_manifests_csv_template_list"""
        pass

    def test_sample_manifests_read(self) -> None:
        """Test case for sample_manifests_read"""
        pass

    def test_sample_manifests_xlsx_template_list(self) -> None:
        """Test case for sample_manifests_xlsx_template_list"""
        pass

    def test_sample_metadata_create(self) -> None:
        """Test case for sample_metadata_create"""
        pass

    def test_sample_metadata_read(self) -> None:
        """Test case for sample_metadata_read"""
        pass

    def test_sample_quality_controls_read(self) -> None:
        """Test case for sample_quality_controls_read"""
        pass

    def test_sample_restore_group_read(self) -> None:
        """Test case for sample_restore_group_read"""
        pass

    def test_sample_sheet_list(self) -> None:
        """Test case for sample_sheet_list"""
        pass

    def test_sample_stats_read(self) -> None:
        """Test case for sample_stats_read"""
        pass

    def test_sample_statuses_read(self) -> None:
        """Test case for sample_statuses_read"""
        pass

    def test_sample_trait_scores_read(self) -> None:
        """Test case for sample_trait_scores_read"""
        pass

    def test_samples_read(self) -> None:
        """Test case for samples_read"""
        pass


if __name__ == "__main__":
    unittest.main()
