# coding: utf-8

"""
    Gencove Back API

    API for Gencove REST service. Visit <a href='https://gencove.com/'>gencove.com</a> and <a href='https://docs.gencove.com/'>docs.gencove.com</a> for more information. <br><hr><p>To work with Insomnia, you can generate a Gencove API key by <a target='_blank' href='https://web.gencove.com/account?filter=api-keys'>clicking here</a>. Once you have the API key and have imported the project in Insomnia as a <i>Request Collection</i>, enter the key in Insomnia under <i>Manage Environment</i>.</p><a href='https://insomnia.rest/run/?label=back_api2&uri=https%3A%2F%2Fv2-api-files-prod.s3.amazonaws.com%2Fpublic%2Finsomnia%2Finsomnia_gencove_prod.json' target='_blank'>Run in Insomnia</a><hr>

    The version of the OpenAPI document: v2
    Contact: info@gencove.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "gencove-client"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.8"
REQUIRES = [
    "urllib3 >= 1.25.3, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Gencove Back API",
    author="OpenAPI Generator community",
    author_email="info@gencove.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Gencove Back API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Proprietary",
    long_description_content_type="text/markdown",
    long_description="""\
    API for Gencove REST service. Visit &lt;a href&#x3D;&#39;https://gencove.com/&#39;&gt;gencove.com&lt;/a&gt; and &lt;a href&#x3D;&#39;https://docs.gencove.com/&#39;&gt;docs.gencove.com&lt;/a&gt; for more information. &lt;br&gt;&lt;hr&gt;&lt;p&gt;To work with Insomnia, you can generate a Gencove API key by &lt;a target&#x3D;&#39;_blank&#39; href&#x3D;&#39;https://web.gencove.com/account?filter&#x3D;api-keys&#39;&gt;clicking here&lt;/a&gt;. Once you have the API key and have imported the project in Insomnia as a &lt;i&gt;Request Collection&lt;/i&gt;, enter the key in Insomnia under &lt;i&gt;Manage Environment&lt;/i&gt;.&lt;/p&gt;&lt;a href&#x3D;&#39;https://insomnia.rest/run/?label&#x3D;back_api2&amp;uri&#x3D;https%3A%2F%2Fv2-api-files-prod.s3.amazonaws.com%2Fpublic%2Finsomnia%2Finsomnia_gencove_prod.json&#39; target&#x3D;&#39;_blank&#39;&gt;Run in Insomnia&lt;/a&gt;&lt;hr&gt;
    """,  # noqa: E501
    package_data={"gencove_client": ["py.typed"]},
)
