# coding: utf-8

"""
    Gencove Back API

    API for Gencove REST service. Visit <a href='https://gencove.com/'>gencove.com</a> and <a href='https://docs.gencove.com/'>docs.gencove.com</a> for more information. <br><hr><p>To work with Insomnia, you can generate a Gencove API key by <a target='_blank' href='https://web.gencove.com/account?filter=api-keys'>clicking here</a>. Once you have the API key and have imported the project in Insomnia as a <i>Request Collection</i>, enter the key in Insomnia under <i>Manage Environment</i>.</p><a href='https://insomnia.rest/run/?label=back_api2&uri=https%3A%2F%2Fv2-api-files-prod.s3.amazonaws.com%2Fpublic%2Finsomnia%2Finsomnia_gencove_prod.json' target='_blank'>Run in Insomnia</a><hr>

    The version of the OpenAPI document: v2
    Contact: info@gencove.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self


class BatchFileNested(BaseModel):
    """
    BatchFileNested
    """  # noqa: E501

    id: Optional[StrictStr] = None
    s3_path: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = Field(
        default=None, description="S3 object key"
    )
    size: Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=-9223372036854775808)]] = Field(
        default=None, description="Size as reported by AWS in bytes"
    )
    download_url: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(
        default=None, description="Download url"
    )
    file_type: Optional[StrictStr] = None
    checksum_sha256: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(
        default=None, description="Object's sha256 Checksum"
    )
    shadow_mode: Optional[StrictBool] = Field(
        default=None, description="If true, file is only accessible by organizations with shadow mode access enabled."
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "s3_path",
        "size",
        "download_url",
        "file_type",
        "checksum_sha256",
        "shadow_mode",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BatchFileNested from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "id",
                "download_url",
                "file_type",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if size (nullable) is None
        # and model_fields_set contains the field
        if self.size is None and "size" in self.model_fields_set:
            _dict["size"] = None

        # set to None if shadow_mode (nullable) is None
        # and model_fields_set contains the field
        if self.shadow_mode is None and "shadow_mode" in self.model_fields_set:
            _dict["shadow_mode"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BatchFileNested from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "s3_path": obj.get("s3_path"),
                "size": obj.get("size"),
                "download_url": obj.get("download_url"),
                "file_type": obj.get("file_type"),
                "checksum_sha256": obj.get("checksum_sha256"),
                "shadow_mode": obj.get("shadow_mode"),
            }
        )
        return _obj
