# coding: utf-8

"""
    Gencove Back API

    API for Gencove REST service. Visit <a href='https://gencove.com/'>gencove.com</a> and <a href='https://docs.gencove.com/'>docs.gencove.com</a> for more information. <br><hr><p>To work with Insomnia, you can generate a Gencove API key by <a target='_blank' href='https://web.gencove.com/account?filter=api-keys'>clicking here</a>. Once you have the API key and have imported the project in Insomnia as a <i>Request Collection</i>, enter the key in Insomnia under <i>Manage Environment</i>.</p><a href='https://insomnia.rest/run/?label=back_api2&uri=https%3A%2F%2Fv2-api-files-prod.s3.amazonaws.com%2Fpublic%2Finsomnia%2Finsomnia_gencove_prod.json' target='_blank'>Run in Insomnia</a><hr>

    The version of the OpenAPI document: v2
    Contact: info@gencove.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from gencove_client.models.project_share_status import ProjectShareStatus
from typing import Optional, Set
from typing_extensions import Self


class ProjectShare(BaseModel):
    """
    ProjectShare
    """  # noqa: E501

    id: Optional[StrictStr] = None
    project: StrictStr
    shared_with_org: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    shared_with_org_name: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    shared_with_user_emails: List[Annotated[str, Field(min_length=1, strict=True)]]
    shared_with_user_email: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    shared_by_user_email: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    share_level: Annotated[str, Field(min_length=1, strict=True, max_length=10)]
    last_status: Optional[ProjectShareStatus] = None
    __properties: ClassVar[List[str]] = [
        "id",
        "project",
        "shared_with_org",
        "shared_with_org_name",
        "shared_with_user_emails",
        "shared_with_user_email",
        "shared_by_user_email",
        "share_level",
        "last_status",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProjectShare from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "id",
                "shared_with_org",
                "shared_with_org_name",
                "shared_with_user_email",
                "shared_by_user_email",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of last_status
        if self.last_status:
            _dict["last_status"] = self.last_status.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProjectShare from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "project": obj.get("project"),
                "shared_with_org": obj.get("shared_with_org"),
                "shared_with_org_name": obj.get("shared_with_org_name"),
                "shared_with_user_emails": obj.get("shared_with_user_emails"),
                "shared_with_user_email": obj.get("shared_with_user_email"),
                "shared_by_user_email": obj.get("shared_by_user_email"),
                "share_level": obj.get("share_level"),
                "last_status": (
                    ProjectShareStatus.from_dict(obj["last_status"]) if obj.get("last_status") is not None else None
                ),
            }
        )
        return _obj
